name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  golint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: golint
        uses: Jerome1337/golint-action@v1.0.3
        with:
          golint-path: "./..."

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: "2.20.2"

      - name: Generate mock classes
        run: |
          mockery --dir api --name Client
          mockery --dir persistence --name User
          mockery --dir persistence --name ChatSession

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout 3m0s

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build
        run: go build -v -o gpt .

      - uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: "2.20.2"

      - name: Generate mock classes
        run: |
          mockery --dir api --name Client
          mockery --dir persistence --name User
          mockery --dir persistence --name ChatSession

      - name: Test
        run: go test --count 1 -timeout 30s -short ./...
